### ISSUE TITLE
React native compatibility ? 

### ISSUE THREAD

**Issue by minamakhtar** [Josh-ES/react-here-maps#7]
Can this component use in react naitve?

**Comment by Josh-ES** [comment]
This component, like most standard React components, cannot be used with React Native at the moment as it relies quite heavily on the DOM. I am investigating the possibility of either somehow making the existing code base React Native-compatible or creating a fork for React Native.

**Comment by Josh-ES** [comment]
Libraries and components for React.js, that are intended to be used in the browser, are completely different in their setup to React Native components. Any HERE maps component for React Native would have to be a completely separate project. I've spotted this in my travels, it might be of interest but I haven't used it personally so I can't vouch for it.

https://www.npmjs.com/package/react-native-heremaps

Closing as not solvable.
